---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  eval = FALSE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
library(knitr)
```

# Code for "Neophytes may promote hybridization and adaptations to a changing planet"

The R Code provided in this repository allows to reproduce the entire data carpentry, analysis and data visualization. Due to large file size the data can be downloaded here:

The script structure follows the figures in the main text.

## Folder structure

1. `00` loads all packages

2. `01` contains the code to check the spatial geographic overlap between hybrid and neophyte incidence.

3. `01b` contains the code to quantify how often naturalizations meet congeners.

4. `02` contains the code to check the taxonomic overlap between hybrid and neophyte incidence, and to visualize the phylogeny

4. `03` contains the code to compare diversification rates in genera with and without neophytes and hybrids

5. `04` contains the code to compare the geographic distribution of neophyte, native and hybrid in relation to the human footprint in the United Kingdom.


## Contact
Please contact us at ingmar.staude@uni-leipzig.de if you have further questions, or information on plants we have not listed yet among conservation gardening species.


